- id: isbn:9791143006370
  type: book
  title: 문학 감정 읽는 AI
  authors:
    - 지해인
    - 김바로
  publisher: 커뮤니케이션북스
  description: 딥러닝 기반 감정 분석으로 이상의 단편 속 감정 흐름을 계량화했다. ‘에피파니’를 정서 패턴에서 포착하고, 비애적 내면 구조를 데이터로 확인했다. 분석 자료를 통해 개방형 문학 연구의 길을 연다.
  date: 2025-8-22
  image: /images/research/문학감정읽는AI.jpg
  buttons:
    # - type: manubot
    #   link: https://greenelab.github.io/meta-review/
    # - type: source
    #   text: Manuscript Source
    #   link: https://github.com/greenelab/meta-review
    # - type: website
    #   link: 
    # - type: LOD
    #   link: 
  tags:
    - 디지털인문학
    - 전산문학연구
    - 감정 분석
  # repo: greenelab/meta-review

- id: lod:KMO201633857
  type: book
  title: 디지털 인문학 입문
  authors:
    - 김현
    - 임영상
    - 김바로
  publisher: 휴북스(HueBooks)
  description: 디지털 인문학이란 정보통신기술의 도움을 받아 새로운 방식으로 수행하는 인문학 연구와 교육, 그리고 이와 관계된 창조적인 저작 활동을 일컫는 말이다. 이것은 전통적인 인문학의 주제를 계승하면서 연구 방법 면에서 디지털 기술을 활용하는 연구, 그리고 예전에는 가능하지 않았지만 컴퓨터를 사용함으로써 시도할 수 있게 된 새로운 성격의 인문학 연구를 포함한다.
  date: 2016-5-31
  image: /images/디지털인문학입문.jpg
  buttons:
    # - type: manubot
    #   link: https://greenelab.github.io/meta-review/
    # - type: source
    #   text: Manuscript Source
    #   link: https://github.com/greenelab/meta-review
    - type: website
      link: https://dh.aks.ac.kr/Edu/wiki/index.php/디지털_인문학_입문
    - type: LOD
      link: http://lod.nl.go.kr/resource/KMO201633857
  tags:
    - 디지털인문학
    - 인문정보학
  # repo: greenelab/meta-review


# 논문 섬네일 추가 원하는 경우 추가
# Haein Ji
- id: doi:10.22936/SH.72..202410.021
  image: /images/research/10.22936_SH.72..202410.021.jpg
